import { TagSelected } from "react-tag-autocomplete";
export const targetAudiences: TagSelected[] = [
{ label: "Software Developers", value: "Software Developers" },
{ label: "Frontend Developers", value: "Frontend Developers" },
{ label: "Backend Developers", value: "Backend Developers" },
{ label: "Mobile Developers", value: "Mobile Developers" },
{ label: "Data Scientists", value: "Data Scientists" },
{ label: "Machine Learning Engineers", value: "Machine Learning Engineers" },
{ label: "Blockchain Developers", value: "Blockchain Developers" },
{ label: "Infrastructure Engineers", value: "Infrastructure Engineers" },
{ label: "Cloud Engineers", value: "Cloud Engineers" },
{ label: "Network Engineers", value: "Network Engineers" },
{ label: "Security Engineers", value: "Security Engineers" },
{ label: "Virtualization Specialists", value: "Virtualization Specialists" },
{ label: "Containerization Specialists", value: "Containerization Specialists" },
{ label: "Monitoring Specialists", value: "Monitoring Specialists" },
{ label: "Automation Engineers", value: "Automation Engineers" },
{ label: "Manual Testers", value: "Manual Testers" },
{ label: "Automation Testers", value: "Automation Testers" },
{ label: "Performance Testers", value: "Performance Testers" },
{ label: "Security Testers", value: "Security Testers" },
{ label: "API Testers", value: "API Testers" },
{ label: "Mobile Testers", value: "Mobile Testers" },
{ label: "DevOps Engineers", value: "DevOps Engineers" },
{ label: "Content Writers", value: "Content Writers" },
{ label: "Technical Writers", value: "Technical Writers" },
{ label: "Non-Technical Writers", value: "Non-Technical Writers" },
{ label: "Bloggers", value: "Bloggers" },
{ label: "Copywriters", value: "Copywriters" },
{ label: "SEO Specialists", value: "SEO Specialists" },
{ label: "Editors", value: "Editors" },
{ label: "Proofreaders", value: "Proofreaders" },
{ label: "Creative Writers", value: "Creative Writers" },
{ label: "Growth Specialists", value: "Growth Specialists" },
{ label: "SEM Specialists", value: "SEM Specialists" },
{ label: "Social Media Managers", value: "Social Media Managers" },
{ label: "Content Marketers", value: "Content Marketers" },
{ label: "Email Marketers", value: "Email Marketers" },
{ label: "Influencer Marketers", value: "Influencer Marketers" },
{ label: "Affiliate Marketers", value: "Affiliate Marketers" },
{ label: "Digital Marketers", value: "Digital Marketers" },
{ label: "Finance Professionals", value: "Finance Professionals" },
{ label: "Accountants", value: "Accountants" },
{ label: "Investment Analysts", value: "Investment Analysts" },
{ label: "Tax Specialists", value: "Tax Specialists" },
{ label: "Auditors", value: "Auditors" },
{ label: "Financial Planners", value: "Financial Planners" },
{ label: "Insurance Specialists", value: "Insurance Specialists" },
{ label: "Risk Managers", value: "Risk Managers" },
{ label: "Business Analysts", value: "Business Analysts" },
{ label: "Tech Enthusiasts", value: "Tech Enthusiasts" },
{ label: "Students", value: "Students" },
{ label: "Educators", value: "Educators" },
{ label: "Small Business Owners", value: "Small Business Owners" },
{ label: "Entrepreneurs", value: "Entrepreneurs" },
{ label: "Startup Founders", value: "Startup Founders" },
{ label: "Project Managers", value: "Project Managers" },
{ label: "Product Managers", value: "Product Managers" },
{ label: "UX/UI Designers", value: "UX/UI Designers" },
{ label: "Graphic Designers", value: "Graphic Designers" },
{ label: "Web Designers", value: "Web Designers" },
{ label: "IT Managers", value: "IT Managers" },
{ label: "System Administrators", value: "System Administrators" },
{ label: "Database Administrators", value: "Database Administrators" },
{ label: "Network Administrators", value: "Network Administrators" },
{ label: "Cybersecurity Experts", value: "Cybersecurity Experts" },
{ label: "DevOps Practitioners", value: "DevOps Practitioners" },
{ label: "Agile Coaches", value: "Agile Coaches" },
{ label: "Scrum Masters", value: "Scrum Masters" },
{ label: "Human Resources Professionals", value: "Human Resources Professionals" },
{ label: "Recruiters", value: "Recruiters" },
{ label: "Talent Acquisition Specialists", value: "Talent Acquisition Specialists" },
{ label: "Operations Managers", value: "Operations Managers" },
{ label: "Sales Professionals", value: "Sales Professionals" },
{ label: "Customer Support Representatives", value: "Customer Support Representatives" },
{ label: "Customer Success Managers", value: "Customer Success Managers" },
{ label: "Marketing Managers", value: "Marketing Managers" },
{ label: "Brand Managers", value: "Brand Managers" },
{ label: "Public Relations Specialists", value: "Public Relations Specialists" },
{ label: "Communications Managers", value: "Communications Managers" },
{ label: "Legal Professionals", value: "Legal Professionals" },
{ label: "Compliance Officers", value: "Compliance Officers" },
{ label: "Healthcare Professionals", value: "Healthcare Professionals" },
{ label: "Medical Researchers", value: "Medical Researchers" },
{ label: "Pharmaceutical Specialists", value: "Pharmaceutical Specialists" },
{ label: "Biotech Engineers", value: "Biotech Engineers" },
{ label: "Environmental Scientists", value: "Environmental Scientists" },
{ label: "Renewable Energy Specialists", value: "Renewable Energy Specialists" },
{ label: "Manufacturing Engineers", value: "Manufacturing Engineers" },
{ label: "Mechanical Engineers", value: "Mechanical Engineers" },
{ label: "Electrical Engineers", value: "Electrical Engineers" },
{ label: "Civil Engineers", value: "Civil Engineers" },
{ label: "Chemical Engineers", value: "Chemical Engineers" },
{ label: "Aerospace Engineers", value: "Aerospace Engineers" },
{ label: "Automotive Engineers", value: "Automotive Engineers" },
{ label: "Architects", value: "Architects" },
{ label: "Interior Designers", value: "Interior Designers" },
{ label: "Urban Planners", value: "Urban Planners" },
{ label: "Construction Managers", value: "Construction Managers" },
{ label: "Real Estate Professionals", value: "Real Estate Professionals" },
{ label: "Property Managers", value: "Property Managers" },
{ label: "Facility Managers", value: "Facility Managers" },
{ label: "Event Planners", value: "Event Planners" },
{ label: "Hospitality Managers", value: "Hospitality Managers" },
{ label: "Travel Agents", value: "Travel Agents" },
{ label: "Tourism Specialists", value: "Tourism Specialists" },
{ label: "Retail Managers", value: "Retail Managers" },
{ label: "Supply Chain Managers", value: "Supply Chain Managers" },
{ label: "Logistics Coordinators", value: "Logistics Coordinators" },
{ label: "Procurement Specialists", value: "Procurement Specialists" },
{ label: "E-commerce Managers", value: "E-commerce Managers" },
{ label: "Fashion Designers", value: "Fashion Designers" },
{ label: "Apparel Merchandisers", value: "Apparel Merchandisers" },
{ label: "Jewelry Designers", value: "Jewelry Designers" },
{ label: "Furniture Designers", value: "Furniture Designers" },
{ label: "Visual Merchandisers", value: "Visual Merchandisers" },
{ label: "Sports Coaches", value: "Sports Coaches" },
{ label: "Fitness Trainers", value: "Fitness Trainers" },
{ label: "Nutritionists", value: "Nutritionists" },
{ label: "Dietitians", value: "Dietitians" },
{ label: "Wellness Coaches", value: "Wellness Coaches" },
{ label: "Yoga Instructors", value: "Yoga Instructors" },
{ label: "Pilates Instructors", value: "Pilates Instructors" },
{ label: "Personal Trainers", value: "Personal Trainers" },
{ label: "Athletes", value: "Athletes" },
{ label: "Sports Managers", value: "Sports Managers" },
{ label: "Entertainment Industry Professionals", value: "Entertainment Industry Professionals" },
{ label: "Actors", value: "Actors" },
{ label: "Musicians", value: "Musicians" },
{ label: "Dancers", value: "Dancers" },
{ label: "Directors", value: "Directors" },
{ label: "Producers", value: "Producers" },
{ label: "Screenwriters", value: "Screenwriters" },
{ label: "Video Editors", value: "Video Editors" },
{ label: "Sound Engineers", value: "Sound Engineers" },
{ label: "Photographers", value: "Photographers" },
{ label: "Videographers", value: "Videographers" },
{ label: "Artists", value: "Artists" },
{ label: "Illustrators", value: "Illustrators" },
{ label: "Animators", value: "Animators" },
{ label: "Game Developers", value: "Game Developers" },
{ label: "Game Designers", value: "Game Designers" },
{ label: "Game Testers", value: "Game Testers" },
{ label: "Esports Players", value: "Esports Players" },
{ label: "Streamers", value: "Streamers" },
{ label: "YouTubers", value: "YouTubers" },
{ label: "Podcasters", value: "Podcasters" }
];
